spring.application.name=ecom-application
server.port=8081

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#setting up Actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#info endpoint

management.info.env.enabled=true
info.app.name=MyNewApp
info.app.description= app built by us
info.app.version=1.0.0

#metrics endpoint
#loggers endpoint
#{
#    "configuredLevel":"DEBUG"
#} IN POSTMAN TO CHANGE LOG LEVELS ON THE HTTPREQUESTE USING POST





